dist: trusty
sudo: required
language: node_js
node_js:
  - node
branches:
  except:
  - gh-pages
notifications:
  email: false
services:
  - docker

jobs:
  include:
    - stage: Build
      name: "Build Docker image"
      install: cd scripts && npm ci && cd ..
      script: node scripts/build
      env:
        # DEPLOY_SETTINGS_JSON='{"CI":[{"type":"docker","options":{"user":"","pass":""}}]}'
        - secure: axsfNJRvzMxFJ82qM1ySMXGXK3H5Z/WyZYATTZ1Hb7y6YdyJiK02V2eosAHl7dBOP493/8lpi6p9AzjzKC0kG3OldPcXz+oazVHj7Y0uLpfeg6tkHWqedDek2q+WbykmKwIuH8AkXZw4bXEVp78TADCCtEtQLaSmMFSifApkttiUjztR3mb8MSZ9CjLIi8bdlR1pV9DX9CzwzNZFFwPmnwTPboSey7qvu23/bIjdZh+AXCVX1tLe5yRle7aganjekkE1lm4VrdAH1EwJo+m9BGQombVIWn/HfM3cbHsoReAObDqeB4oIZ4HzOUW3ANa1788JeTak/71p0iSmAhUvtQOOMjEKDY1UmHrZRvwq09jHLUnTPRlJboUn0nnTyR67D8nllApWm5+LFYq912jOmDdBESC64yY965K21XQ0nMo2fQRddx8tMoupq2CvGchV5pqfKAcVU3mL4pR5Nr3VE/ixd93LLrbsvj39L2JNshKrl6yGzhRype0MES2Jw8V+FXEQPoXMGBpbLP3RMydmOHo7ifKduTn8qlAFOb/NyT6giWw6A+R6EbrYZ+BOpLf+CQv1xZrnMyH3GUWNRaloMBczgWaohqL+3JqHkthk1Re5phswhEsK8pQ65D1FXG+O4y8P1ScaTC7wuLkPCChxYF0p8WUc6+AS3OU8YcG3BOs=
    - stage: Test
      name: Unit Tests
      install: cd scripts && npm ci && cd ..
      script: echo ToDo
    - name: "Telegram Bot - Integration Tests"
      install:
        - cd scripts && npm ci && cd ..
        - docker pull poulad/busvbot:unstable-solution
      env:
        - image_tag=poulad/busvbot:unstable-solution
      script: node scripts/test/telegram.integration.test.js
    - stage: Deploy
      name: "Deploy"
      script: skip
      install:
        - cd scripts && npm ci && cd ..
        - docker pull poulad/busvbot:unstable
      env:
        # DEPLOY_SETTINGS_JSON='{"Production":[
        #   {"type":"docker","options":{"source":"poulad/busvbot:unstable","target":"poulad/busvbot:latest","user":"","pass":""}},
        #   {"type":"heroku","options":{"app":"busvbot","source":"poulad/busvbot:latest","dyno":"web","user":"","token":""}}
        # ]}'
        - secure: Z7zjHuFe7zkATfNUUonVuQvsrZIj3x1yyPCToEwSx1VFvnsrsyCtvkoSjxkIg92MdLlt0RUQHXNXygKl6DKIBudIuIAHpXNP01MEe674jr4xMqm7d86JRdB1NkielY85IjPXv4dvt540MoMgVb3MuiifHIHgfPnb2g4QzBPpKHYZLOGBGZEA/4TkA44z1Mre1adKKl5GUnq6N0jdYzbrNigR5lMKeTei+jE4dh1P81zJPSMhWYRZw8wUlT2b8R9MkuSbBGNa0XWQVq163pnHg5JyiydbZAcfWJR2u2sQTrfjqjt0J14W0k72JaRhhRXRCAW6eJFXzaFMv4cEpgpvdtXJOjMp46JUOj/Mw7bejlXGmbkW5syuzOi/Q/jKZ60lqej1WfkhkqJH+VGeKboNeaJgjjnQN/tdc/UFLT6KpplWK4huCauyaUEoO4MeXiqk0a2o2lEvLlP++10rZadJH/u5ESxT/G89Hhlk+H1EBcgJf81Yy3Cvzya7xRD6i+27mG4pMmxPRqbOM0nYwPu8hxYw8LxEXKxVX7xHwg65gHCitScvqmBIIp5DgDliimCGDE/5x8GBF2ANULsGoqCZt4S1vATuur82gQ4uUsxZtLYrdoRp8RGyu4rC06m5VLUE6P8GIPtHmOJI1RzcaXXb3s44BQqXLPbOFK+LQyIUWSo=
      deploy:
        - provider: script
          skip_cleanup: true
          script: node scripts/deploy Production
          on:
            branch: master


# Disable "Build pushed pull requests"
