version: '2'

services:
  busvbot:
    container_name: busvbot
    build:
      context: ../src/BusVbot
      args:
        project: BusVbot
    expose:
      - "80"
    restart: on-failure
    networks:
      BusVbot-network:
        ipv4_address: 172.16.238.10

networks: 
  BusVbot-network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1